---
- hosts: spot_core
  remote_user: spot

  vars_files:
    - vars/main.yml

  tasks:
    - import_tasks: tasks/update.yml
      become: true
      become_method: sudo

    - import_tasks: tasks/prevent_access.yml
      become: true
      become_method: sudo

    - import_tasks: tasks/enable_access.yml
      become: true
      become_method: sudo

    - import_tasks: tasks/install_wifi.yml
      become: true
      become_method: sudo

    - import_tasks: tasks/network_config.yml
      become: true
      become_method: sudo

    - name: Reboot the machine (This doesn't work correctly)
      reboot:
        reboot_timeout: 60
      become: true
      become_method: sudo
