---
- name: Set the hostname to spot.dhcp.fnal.gov for Kerberos
  ansible.builtin.hostname:
    name: spot.dhcp.fnal.gov

- name: Add self to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost spot'
    state: present
